wandb_version: 1

train_name:
  desc: null
  value: whisper
audio_max_length:
  desc: null
  value: 160000
text_max_length:
  desc: null
  value: 300
accelerator:
  desc: null
  value: auto
weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
num_worker:
  desc: null
  value: 16
validate_every_n_batches:
  desc: null
  value: 1000
num_devices:
  desc: null
  value: 1
precision:
  desc: null
  value: 16-mixed
model_name:
  desc: null
  value: tiny
learning_rate:
  desc: null
  value: 1.0e-05
batch_size:
  desc: null
  value: 16
num_train_steps:
  desc: null
  value: 50000
warmup_steps:
  desc: null
  value: 500
gradient_accumulation_steps:
  desc: null
  value: 1
monitor:
  desc: null
  value: dev/acc
noise_prob:
  desc: null
  value: 0.0
spec_augment:
  desc: null
  value: ls-basic
dropout_rate:
  desc: null
  value: 0
lang:
  desc: null
  value: en
resume_training:
  desc: null
  value: false
train_id:
  desc: null
  value: whisper_en-x_tiny
log_output_dir:
  desc: null
  value: slurm/train_audio_slurm
check_output_dir:
  desc: null
  value: models/checkpoints
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723641830
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 100
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 100
      - 103
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.17.6
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
