train_name: whisper
audio_max_length: 480000 # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: tiny
learning_rate: 1.0e-4 
batch_size: 16
num_train_steps: 40000
warmup_steps: 5000
gradient_accumulation_steps: 1

monitor: 'dev-other/acc_at'  
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0 

lang: en
resume_training: False

# pt_ckpt: 'whisper_en_tiny/step-05000-wer=0.0000-acc=0.0000.ckpt'
pt_ckpt: ''
train_id: whisper-flamingo_en_tiny_without_special_tokens

prob_use_at: 1.0 # For Whisper-Flamingo, no modality dropout

# text
add_gated_x_attn: 1 # 0 for False, 1 for True

translation_base_dir: "/share/nas169/jerryyang/corpus/m2m100/chinese"
log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"


