train_name: whisper
audio_max_length: 480000  # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 2
precision: 16-mixed

model_name: small
learning_rate: 1.0e-5
batch_size: 8
num_train_steps: 80000
warmup_steps: 8000
gradient_accumulation_steps: 1

monitor: 'avg_eval/wer_at'
noise_prob: 0.0

dropout_rate: 0

lang: id
config_names: "卑南_南王+卑南_建和+卑南_知本+卑南_西群+卡那卡那富+噶瑪蘭+太魯閣+布農_丹群+布農_卓群+布農_卡群+布農_巒群+布農_郡群+拉阿魯哇+排灣_中+排灣_北+排灣_南+排灣_東+撒奇萊雅+泰雅_四季+泰雅_宜蘭澤敖利+泰雅_汶水+泰雅_澤敖利+泰雅_萬大+泰雅_賽考利克+賽夏+賽德克_德固達雅+賽德克_德鹿谷+賽德克_都達+邵+鄒+阿美_南勢+阿美_恆春+阿美_海岸+阿美_秀姑巒+阿美_馬蘭+雅美+魯凱_多納+魯凱_大武+魯凱_東+魯凱_茂林+魯凱_萬山+魯凱_霧台"
# config_names: "卑南_南王+卑南_建和+卑南_知本+卑南_西群"
eval_config_names: "卑南_南王+卑南_建和+卑南_知本+卑南_西群+卡那卡那富+噶瑪蘭+太魯閣+布農_丹群+布農_卓群+布農_卡群+布農_巒群+布農_郡群+拉阿魯哇+排灣_中+排灣_北+排灣_南+排灣_東+撒奇萊雅+泰雅_四季+泰雅_宜蘭澤敖利+泰雅_汶水+泰雅_澤敖利+泰雅_萬大+泰雅_賽考利克+賽夏+賽德克_德固達雅+賽德克_德鹿谷+賽德克_都達+邵+鄒+阿美_南勢+阿美_恆春+阿美_海岸+阿美_秀姑巒+阿美_馬蘭+雅美+魯凱_多納+魯凱_大武+魯凱_東+魯凱_茂林+魯凱_萬山+魯凱_霧台"
# eval_config_names: "卑南_南王+卑南_建和+卑南_知本+卑南_西群"
resume_training: false

pt_ckpt: 'whisper_finetune_kloka_crawled/step-96000-wer=0.2246.ckpt'
# pt_ckpt: 'whisper_finetune_kloka_crawled/step-57000-wer=0.2351-v1.ckpt'
train_id: whisper-flamingo_kloka_crawled
# train_id: whisper-flamingo_kloka_crawled_few_steps_test

# text
add_gated_x_attn: 1 # 0 for False, 1 for True
num_langs: 1

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-wer_at={avg_eval/wer_at:.4f}"
