train_name: whisper
audio_max_length: 480000  # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 3.0e-5
batch_size: 4
num_train_steps: 100000
warmup_steps: 15000
gradient_accumulation_steps: 1

monitor: 'eval/wer_at'
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0

lang: id
config_names: '阿美_南勢+阿美_恆春+阿美_海岸+阿美_秀姑巒+阿美_馬蘭'
resume_training: false

pt_ckpt: 'whisper_finetune_amis/step-174000-wer=0.1215.ckpt'
train_id: whisper-flamingo_amis (lr=3.0e-5, ws=15k)

# text
add_gated_x_attn: 1 # 0 for False, 1 for True
num_langs: 1

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-wer_at={eval/wer_at:.4f}"
