train_name: whisper
audio_max_length: 160000 # 10 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 1.0e-6
batch_size: 8
num_train_steps: 180000
warmup_steps: 30000
gradient_accumulation_steps: 1

monitor: 'val/cer_at'  
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0 

lang: zh
resume_training: False

pt_ckpt: 'whisper_taigi_small/step-78000-cer=0.1811-wer=0.6140.ckpt'
train_id: kg-whisper-flamingo_lr=1.0e-6_max_keywords=9999

# text
add_gated_x_attn: 1 # 0 for False, 1 for True
bert_encoder: True
mode: "translation"

# prompt
prompt: 1 # 0 for False, 1 for True
max_keywords_for_prompt: 9999
adakws_checkpoint: '/share/nas169/jerryyang/whisper-flamingo/models/checkpoints/tmp_best/step-142000-f1=0.8640.ckpt'

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-cer_at={val/cer_at:.4f}"
