train_name: whisper
audio_max_length: 480000 # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 4000
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 1.0e-6 # small
batch_size: 4
num_train_steps: 480000
warmup_steps: 48000
gradient_accumulation_steps: 1

monitor: 'dev-other/wer_at'
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0 

lang: en
resume_training: False

pt_ckpt: 'whisper_en-x_small/step-27000-cer=0.0297-wer=0.0575.ckpt'
train_id: translation_prompt_librispeech (lr=1.0e-6)

# flamingo
add_gated_x_attn: 0 # 0 for False, 1 for True
num_langs: 0

# prompt
prompt: 1 # 0 for False, 1 for True

translation_base_dirs:
  - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/Mandarin Chinese"
log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-cer_at={val/cer_at:.4f}"
