train_name: whisper
audio_max_length: 480000 # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 200
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 1.0e-6
batch_size: 8
num_train_steps: 20000
warmup_steps: 2000
gradient_accumulation_steps: 1

monitor: 'eval/wer_at'
noise_prob: 0.0
noise_snr_train: 0

dropout_rate: 0 

lang: id
config_names: '阿美_秀姑巒'
resume_training: False

teacher_ckpt: 'Trans-ASR_amis_siwkulan_bilingual/step-05900-wer_at=0.1264.ckpt'
train_id: transkd-asr_amis_siwkulan_bilingua

# text
add_gated_x_attn: 1 # 0 for False, 1 for True
num_langs: 2

translation_csv_train: "/share/nas169/jerryyang/whisper-flamingo/translation/阿美_秀姑巒_translated_ind_train.csv"
translation_csv_eval: "/share/nas169/jerryyang/whisper-flamingo/translation/阿美_秀姑巒_translated_ind_eval.csv"

# distil
freeze_encoder: 1
alpha: 0.8
beta: 1.0
temperature: 2.0
use_pseudo_labels: True
pseudo_csv_path_train: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/kloka_crawled/flamingo/amis_siwkulan_bilingual_train.csv

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-wer_at={eval/wer_at:.4f}"
