model_name: small
audio_max_length: 160000
dropout_rate: 0
batch_size: 16
num_worker: 16
lang: zh

# Flamingo
add_gated_x_attn: 0
bert_encoder: false
mode: ""

# path
teacher_ckpt: 'translation_prompt(lr=1.0e-6)/step-169000-cer_at=0.1232.ckpt' 
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/yttd_taigi_trs/distil-whisper+prompt