model_name: small
audio_max_length: 160000
dropout_rate: 0
add_gated_x_attn: 1
bert_encoder: true
mode: translation
teacher_ckpt: 'whisbert-flamingo_taigi_small/step-178000-cer_at=0.1617.ckpt'
batch_size: 16
num_worker: 16
lang: zh
# cer_threshold: 20