model_name: small
audio_max_length: 480000 # 30 sec
dropout_rate: 0
num_worker: 16
batch_size: 16
lang: en

# Flamingo
add_gated_x_attn: 0 # 0 for False, 1 for True
bert_encoder: False
mode: ""

# path
teacher_ckpt: 'translation_prompt_librispeech (lr=1.0e-6)/step-216000-cer_at=0.0000.ckpt'
translation_base_dirs:
  - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/Mandarin Chinese"
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/prompt/cmn
