model_name: small
audio_max_length: 480000
dropout_rate: 0
batch_size: 16
num_worker: 16
lang: id

# config_names: "太魯閣"
# config_names: '阿美_秀姑巒'
config_names: "賽德克_德固達雅"
# file_name: "truku_bilingual"
# file_name: "amis_siwkulan_bilingual"
file_name: "seediq_Tgdaya_bilingual"

# Flamingo
add_gated_x_attn: 1
num_langs: 2

# translation_csv_train: "/share/nas169/jerryyang/whisper-flamingo/translation/太魯閣_translated_ind_train.csv"
# translation_csv_eval: "/share/nas169/jerryyang/whisper-flamingo/translation/太魯閣_translated_ind_eval.csv"
# translation_csv_train: "/share/nas169/jerryyang/whisper-flamingo/translation/阿美_秀姑巒_translated_ind_train.csv"
# translation_csv_eval: "/share/nas169/jerryyang/whisper-flamingo/translation/阿美_秀姑巒_translated_ind_eval.csv"
translation_csv_train: "/share/nas169/jerryyang/whisper-flamingo/translation/賽德克_德固達雅_translated_ind_train.csv"
translation_csv_eval: "/share/nas169/jerryyang/whisper-flamingo/translation/賽德克_德固達雅_translated_ind_eval.csv"


# path
# teacher_ckpt: 'Trans-ASR_truku_bilingual/step-13200-wer_at=0.0904.ckpt'
# teacher_ckpt: 'Trans-ASR_amis_siwkulan_bilingual/step-05900-wer_at=0.1264.ckpt'
teacher_ckpt: 'Trans-ASR_seediq_Tgdaya_bilingual/step-02000-wer_at=0.1270.ckpt'
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/kloka_crawled/flamingo
