model_name: small
audio_max_length: 480000 # 30 sec
dropout_rate: 0
num_worker: 16
batch_size: 16
lang: en

# Flamingo
add_gated_x_attn: 1 # 0 for False, 1 for True
num_langs: 1
# num_langs: 2
# num_langs: 3
# num_langs: 4

# path
# teacher_ckpt: 'monolingual/step-216000-wer_at=0.0510.ckpt'
# teacher_ckpt: 'bilingual/step-356000-wer_at=0.0465.ckpt'
# teacher_ckpt: 'trilingual/step-212000-wer_at=0.0449.ckpt'
# teacher_ckpt: 'quadrilingual/step-284000-wer_at=0.0424.ckpt'
teacher_ckpt: 'monolingual_deu/step-216000-wer_at=0.0484.ckpt'

translation_base_dirs:
  # - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/Mandarin Chinese"
  - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/German"
  # - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/French"
  # - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/Italian"

# output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/flamingo/monolingual
# output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/flamingo/bilingual
# output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/flamingo/trilingual
# output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/flamingo/quadrilingual
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/flamingo/monolingual_deu
