model_name: small
# audio_max_length: 640000 # 40 sec
audio_max_length: 480000 # 30 sec
dropout_rate: 0
num_worker: 16
batch_size: 16
lang: en

# Flamingo
add_gated_x_attn: 1 # 0 for False, 1 for True
bert_encoder: True
# mode: "bilingual"
mode: "translation"

# path
# teacher_ckpt: 'whisbert-flamingo_en-cmn+en-deu_small/step-356000--wer_at=0.0468.ckpt'
teacher_ckpt: 'whisbert-flamingo_en-deu_small/step-284000-cer_at=0.0244-wer_at=0.0481.ckpt'
translation_base_dirs:
  # - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/Mandarin Chinese"
  - "/share/nas169/jerryyang/corpus/seamlessm4t/LibriSpeech/German"
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/librispeech/deu