model_name: small
audio_max_length: 160000
dropout_rate: 0
batch_size: 16
num_worker: 16
lang: zh

# Flamingo
add_gated_x_attn: 1
bert_encoder: true
mode: translation

# path
# teacher_ckpt: 'whisbert-flamingo_taigi_small/step-178000-cer_at=0.1617.ckpt'
teacher_ckpt: 'whisbert-flamingo_taigi_small(num_train_steps=60k, warmup_steps=10k)/step-54000-cer_at=0.1754.ckpt'
output_dir: /share/nas169/jerryyang/whisper-flamingo/pseudo_labels/yttd_taigi_trs/distil-whisper