train_name: adakws
audio_max_length: 160000 # 10 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

whisper_size: small
lr_classifier: 1.0e-4
lr_text: 1.0e-4
batch_size: 4
num_train_steps: 300000
warmup_steps: 50000
gradient_accumulation_steps: 1

monitor: 'val/f1'  
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0 

lang: zh
resume_training: False

pt_ckpt: '/share/nas169/jerryyang/whisper-flamingo/models/checkpoints/tmp_best/step-160000-f1=0.8662.ckpt'
train_id: adakws

# prob_use_at: 1.0 # For Whisper-Flamingo, no modality dropout

# text
add_gated_x_attn: 0 # 0 for False, 1 for True
bert_encoder: False
mode: ""
sequential_gated_x_attn: False # False for parallel flamingo

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-f1={val/f1:.4f}"
