train_name: whisper
audio_max_length: 480000  # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 2000
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 1.25e-5  # small
batch_size: 2
num_train_steps: 190000
warmup_steps: 19000
gradient_accumulation_steps: 1

monitor: 'eval/wer'
noise_prob: 0.0

spec_augment: ""
dropout_rate: 0

lang: id
resume_training: false

pt_ckpt: ''
train_id: whisper_finetune_amis

log_output_dir: "slurm/train_audio_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-wer={eval/wer:.4f}"
