train_name: whisper
audio_max_length: 480000  # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: tiny
learning_rate: 3.75e-5
batch_size: 8
num_train_steps: 240000
warmup_steps: 24000
gradient_accumulation_steps: 1

monitor: 'dev-other/wer'  
noise_prob: 0.0  

spec_augment: "" 
dropout_rate: 0

lang: en
resume_training: false

pt_ckpt: ''
train_id: whisper_en_tiny_

log_output_dir: "slurm/train_audio_slurm"
check_output_dir: "models/checkpoints"
