train_name: whisper
audio_max_length: 480000  # 30 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: tiny  
learning_rate: 1.25e-5  # small
batch_size: 16
num_train_steps: 40000
warmup_steps: 1000
gradient_accumulation_steps: 1

monitor: 'val/acc'  
noise_prob: 0.0  

spec_augment: "" 
dropout_rate: 0

lang: zh
resume_training: false

pt_ckpt: 'whisper_taigi_tiny/step-10000-wer=0.0000-acc=0.0000.ckpt'
# pt_ckpt: ''
train_id: whisper_taigi_tiny

log_output_dir: "slurm/train_audio_slurm"
check_output_dir: "models/checkpoints"
