train_name: whisper
audio_max_length: 560000  # 35 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 100
num_devices: 1
precision: 16-mixed

model_name: tiny  
learning_rate: 1.25e-5  # small
batch_size: 16
num_train_steps: 1000
warmup_steps: 100
gradient_accumulation_steps: 1

monitor: 'validation/wer'  
noise_prob: 0.0  

spec_augment: "" 
dropout_rate: 0

lang: en
resume_training: false

# pt_ckpt: 'whisper_en_tiny_fleurs/step-00300-cer=0.0660-wer=0.1250.ckpt'
pt_ckpt: ''
train_id: whisper_en_tiny_fleurs

log_output_dir: "slurm/train_audio_slurm"
check_output_dir: "models/checkpoints"
